//app state types
export const app = {
  UPDATE_CONN: 'UPDATE_CONN',
  WELCOMED: 'WELCOMED',
  PREV_PATH: 'PREV_PATH'
};

export const geo = {
  SET_AVAIL: 'SET_AVAIL',
  SET_HERE: 'SET_HERE',
  SET_HERE: 'SET_HERE_FROM_IP',
  GEO_ERROR: 'GEO_ERROR'
};

export const walk = {
  SET_BOX: 'SET_BOX',
  SAVE_PARAMS: 'SAVE_PARAMS',
  SAVE_WALKS: 'SAVE_WALKS',
  SAVE_MY_WALKS: 'SAVE_MY_WALKS',
  SAVE_WALK: 'SAVE_WALK',
  SAVE_ROUTE: 'SAVE_ROUTE',
  SAVE_STOPS: 'SAVE_STOPS',
  SAVE_STOP_IDX: 'SAVE_STOP_IDX',
  CURRENT_MANEUVER: 'CURRENT_MANEUVER'
};

export const auth = {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_SUBMIT: 'CLEAR_SUBMIT',
  CLEAR_ERROR: 'CLEAR_ERROR',
  AUTH_ROUTE: 'AUTH_ROUTE',
  SHOW_LOADER: 'SHOW_LOADER'
};

export const form = {
  LOAD_COMMON: 'LOAD_COMMON',
  CREATE_GO_NEXT: 'CREATE_GO_NEXT',
  SAVE_PAGE_IDX: 'SAVE_PAGE_IDX'
};

export const nav= {
  CHANGE_ROUTE: 'CHANGE_ROUTE',
  GO_BACK: 'GO_BACK',
  REQUEST_ROUTE: 'REQUEST_ROUTE',
  ROUTE_LOADED: 'ROUTE_LOADED'
};