//app state types
export const app = {
  ADD_ROUTE_TO_HISTORY: 'ADD_ROUTE_TO_HISTORY',
  DELETE_LAST_ROUTE: 'DELETE_LAST_ROUTE'
};

export const geo = {
  SET_AVAIL: 'SET_AVAIL',
  SET_HERE: 'SET_HERE',
  SET_HERE: 'SET_HERE_FROM_IP',
  UPDATE_MSG: 'UPDATE_MSG'
};

export const search = {
  LOAD_SEARCH_FORM: 'LOAD_SEARCH_FORM',
  SET_BOX: 'SET_BOX',
  SAVE_PARAMS: 'SAVE_PARAMS',
  SAVE_WALKS: 'SAVE_WALKS',
  SAVE_WALK: 'SAVE_WALK',
  SAVE_ROUTE: 'SAVE_ROUTE'
};

export const auth = {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_SUBMIT: 'CLEAR_SUBMIT',
  CLEAR_ERROR: 'CLEAR_ERROR'
};