//app state types
export const app = {
  UPDATE_CONN: 'UPDATE_CONN'
};

export const geo = {
  SET_AVAIL: 'SET_AVAIL',
  SET_HERE: 'SET_HERE',
  SET_HERE: 'SET_HERE_FROM_IP',
  GEO_ERROR: 'GEO_ERROR'
};

export const search = {
  SET_BOX: 'SET_BOX',
  SAVE_PARAMS: 'SAVE_PARAMS',
  SAVE_WALKS: 'SAVE_WALKS',
  SAVE_WALK: 'SAVE_WALK',
  SAVE_ROUTE: 'SAVE_ROUTE'
};

export const auth = {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_SUBMIT: 'CLEAR_SUBMIT',
  CLEAR_ERROR: 'CLEAR_ERROR',
  AUTH_ROUTE: 'AUTH_ROUTE',
  SHOW_LOADER: 'SHOW_LOADER'
};

export const form = {
  LOAD_COMMON: 'LOAD_COMMON',
  CREATE_GO_NEXT: 'CREATE_GO_NEXT',
  SAVE_PAGE_IDX: 'SAVE_PAGE_IDX'
};